#framework:
#    security:
#        password_hashers:
#            # auto hasher with default options for the User class (and children)
#            Domain\Model\Entity\User\User: 'auto'
#
#            # auto hasher with custom options for all PasswordAuthenticatedUserInterface instances
#            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
#                algorithm: 'auto'
#                cost:      15
