# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

imports:
    - { resource: services/application/kernel_event_listeners.yaml }
    - { resource: services/application/message-bus-middlewares.yaml }
    - { resource: services/domain/repositories.yaml }
    - { resource: services/domain/validation.yaml }
    - { resource: services/infrastructure/param_converters.yaml }
    - { resource: services/infrastructure/responders.yaml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        # Automatically injects dependencies in your services.
        autowire: true
        # Automatically registers your services as commands, event subscribers, etc.
        autoconfigure: false
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
#    Application\:
#        resource: '../src/Application'
#        exclude:
#            - '../src/Application/Kernel.php'
#
#    Domain\:
#        resource: '../src/Domain'
#        exclude:
#            - '../src/Domain/Model/Entity'
#
#    Infrastructure\:
#        resource: '../src/Infrastructure'

    # controllers are imported separately to make sure they
    # have the tag that allows actions to type-hint services
    Infrastructure\Http\Controller\:
        resource: '../src/Infrastructure/Http/Controller'
        tags: [ 'controller.service_arguments' ]

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # move this to an import (use ../../../)
    Application\CommandHandler\:
        resource: '../src/Application/CommandHandler'
        tags: [ 'messenger.message_handler' ]
